### ISSUE TITLE
Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#280] opened 2022-10-13 14:37 UTC
**Describe the bug**
When using Baklava components for React from npm package this alert appears and breaks the page
`Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')`

**To Reproduce**
1. Import Baklava Component from /baklava-react
2. See error

**Additional context**
When debugging using browser it appears to be error caused from this set of code
```js
// Set of properties/events which should be specially handled by the wrapper
  // and not handled directly by React.
  const elementClassProps = new Set(Object.keys(events ?? {}));
  for (const p in elementClass.prototype) {
    if (!(p in HTMLElement.prototype)) {
      if (reservedReactProperties.has(p)) {
        // Note, this effectively warns only for `ref` since the other
        // reserved props are on HTMLElement.prototype. To address this
        // would require crawling down the prototype, which doesn't feel worth
        // it since implementing these properties on an element is extremely
        // rare.
        console.warn(
          `${tagName} contains property ${p} which is a React ` +
            `reserved property. It will be used by React and not set on ` +
            `the element.`
        );
      } else {
        elementClassProps.add(p);
      }
    }
  }
```

and `elementClass` is undefined thus the error occurs. It seem to be the issue is caused by bl-pagination component even if you not use it in the project.

**Versions**
React 18.2.0
Baklava v2.0.0-beta.38
Vite 3.1.0

**Comment by olkeoguz** [comment] 2022-10-13 14:55
@AykutSarac  Could you reproduce the error in a sandbox ?
I created one and did not get any errors. Maybe this is an error occurring in a certain situation ?
https://codesandbox.io/s/react-typescript-forked-c06u5d?file=/src/App.tsx

**Comment by muratcorlu** [comment] 2022-10-13 15:16
And another important question: which baklava version are you using?

**Comment by AykutSarac** [comment] 2022-10-14 07:28
> And another important question: which baklava version are you using?

I'm using beta.38.

**Comment by olkeoguz** [comment] 2022-10-14 12:00
The error occurs when cdn version is beta.33 and npm version is beta.38 as below.
https://codesandbox.io/s/react-typescript-forked-c06u5d?file=/public/index.html

So this one turns into a seller center spesific issue. We can discuss it internally.

**Comment by muratcorlu** [comment] 2022-10-17 11:55
It's nice that we noticed this. I created a PR to mention that point on React implementation document.

But, I still see a risk about that to be honest. In an micro frontend architecture, when Baklava is installed on wrapper and React app bundled separately, increasing the minor version of the baklava in wrapper should not break sub React apps. I hope this break is because we made breaking changes on Button component.

**Comment by leventozen** [comment] 2022-10-17 16:05
We talked to @AykutSarac and seems like the problem still persists. After researching the issue /w @olkeoguz, looks like this issue happens when "micro react" project is initialized before the baklava CDN is properly imported by the `shell` project.
The version difference warning which @muratcorlu mentioned is merged already. However, this is kind of a project-specific issue and should be resolved in the project itself. Tomorrow, we will examine this deeply to be 100% sure.

**Closed** 2022-10-17 16:11 UTC
