### ISSUE TITLE
Documentation - How to use typography?

### ISSUE THREAD

**Issue by DamlaDemir** [Trendyol/baklava#235] opened 2022-09-13 06:23 UTC
Heading variables (heading1, heading2, heading3) in our typography system are missing, these variables should be added. And the documentation is unsatisfactory for development. We should describe the variable names and their styles in the documentation. When looking at the documentation, typography variables and their styles should be easily found.

https://www.figma.com/file/lSvX6Qe0jc8b4CaIK7egXR/Baklava-Component-Library?node-id=240%3A124

**Comment by muratcorlu** [comment] 2022-09-13 08:23
Linked Figma document is private. Typography rules should be moved to [the public Figma document](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=4%3A5583) @buseselvi

**Comment by muratcorlu** [comment] 2022-09-13 11:27
Looks like a duplicate of #92

**Comment by buseselvi** [comment] 2022-09-16 07:53
We added the typography document to the public Figma document: (https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=1564%3A6892)

**Closed** 2022-10-03 07:05 UTC
Labels: documentation, baklava-ds
